### PR TITLE
Explain !

### PR DESCRIPTION
**Pull request by ghost**
This file was the first time I saw `!`, and people, myself included, asked on Slack about `!` from seeing this file.

### CODE REVIEW

**Comment by willisplummer** [comment]
thanks for opening this pr! was just looking for this info 👍

**Comment by ivanvotti** [comment]
http://klaftertief.github.io/elm-search/?q=!

**Comment by willnwhite** [comment]
Or search for ! in core on package.elm-lang.org. Both give us

screenshot 2016-09-22 14 13 24

It helps to know that `(!)` is non-infix notation (prefix?), and that the second Cmd msg is the List of Cmd msgs as one.

**Comment by willnwhite** [comment]
https://github.com/elm-lang/core/pull/719

**Pull request closed without merging**
