### PR TITLE
Make todo <li> elements keyed by id. Fixes #1

### LINKED ISSUE #1: Tapping the checkbox in a filtered view changes the following checkbox
Steps to reproduce:

1. Add two items
2. Go to "Active"
3. Click the first item's checkbox

Result: [Screenshot](https://cloud.githubusercontent.com/assets/516527/3646278/44a6eac8-10f2-11e4-9561-979f87ac9db6.png)

### PR DESCRIPTION
**Pull request by llelf**

### CODE REVIEW

**Comment by passy** [comment]
I tried this against the TodoMVC example, but it doesn't seem to help. Has something else changed I need to take into account? https://gist.github.com/passy/f911d2e4f6fb319acf30

**Comment by llelf** [comment]
Works for me. Just tried in FF, Chrome & Safari.

**Comment by evancz** [comment]
@passy, if it's working for @llelf, my only guess is some sort of configuration / build artifact weirdness. If you clear things out of elm-stuff/ is it still messed up? Is there any configuration info (like version numbers listed in elm-stuff/exact-dependencies.json) that we can compare with @llelf's situation?

**Comment by evancz** [comment]
Will add this when a new version of elm-lang/html comes out that makes it easier

**Pull request closed without merging**
