### PR TITLE
Change visibility based on page hash change

### PR DESCRIPTION
**Pull request by crodjer**
Listening on hash change event to update the app visibility accordingly.
Also, use the URL instead of stored model for getting initial
visibility. The browser back/forward buttons as well work now.

I am new to Elm, so my changes might not be the most ideal way to do things.

### CODE REVIEW

**Comment by crodjer** [comment]
Okay, noticed a issue with this. This works when updating the URL hash for already open app, but for a freshly opened app, the stored visibility is restored. Trying to figure out a fix for this.

**Comment by crodjer** [comment]
The previous commit fixes the issue with newly opened tabs. Basically, I fire one path signal right away.

**Comment by passy** [comment]
Would like to see this functionality again. I've been working on getting the example for todomvc.com updated to `0.15.1` and this is missing from this version to make it spec-compliant.

**Comment by evancz** [comment]
Thanks. Things are a bit different now, so we can add this again once we have a history library in the `elm-lang` organization.

**Pull request closed without merging**
